### ISSUE TITLE
[Suggestion] New Logo for Wiktor Navigator

### ISSUE THREAD

**Issue by zularizal** [syrop/Wiktor-Navigator#1]
Hello @syrop , I want contribute to New Logo for Wiktor Navigator, so i designed a logo for Wiktor Navigator and It's free. I hope you like it.

If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it. 
You can choose color you like.

![logo](https://user-images.githubusercontent.com/38547278/39535496-3dc9eab8-4e5e-11e8-9271-856aecb7eed2.png)

**Comment by zularizal** [comment]
Hi, @syrop  What do you think about this?

**Comment by syrop** [comment]
I see the point you are making thru this icon. You are combining the sharing sign with the navigation sign I already use. Could you however follow the material design product guidelines? Your own "Z" icon is perfect, with shadow pointing in the correct direction and no rainbow background. And please remove the white frame.

Even if you just remove the rainbow and replace it with either a solid color, or make it completely transparent, depending on what you see fit, it will be already prepared for a pull request. Please note that it will not be in Android Play Store before I finish adding debug functionality to the app.

I have no interest in monetizing this app, or promoting it any further, as I merely wrote it as a demonstration of using Firebase to send data between two phones. I am already working on the "Events" app that will be used to advertise local religious events. The new app only works with Android 8 and up, though, as before I finish the app in a few years, Oreo may be already more popular.

I am still working on debug functionality for Navigator, as my girlfriend cannot use it on her new phone. I am trying to check whether it is due to her case blocking the location sensor or due to lack of internet connectivity.

Could you give me a synopsis of your own profile, and what you are trying to achieve thru your projects? What attracted you to Navigator?

**Comment by zularizal** [comment]
I think this app is good. Some people may want to monetize their project, but you do not do it, you are great for this. I like you.

Because this project is open source, so I am interested to make free logo design. I want to help you with the design. And this is the logo I've created for this app. This logo is adaptive. and suitable for os android oreo.
Which color do you like?

![text4607](https://user-images.githubusercontent.com/38547278/40627398-fe3b366e-62e8-11e8-9890-af1ae4f04c42.png)

**Comment by syrop** [comment]
The color number 6 is gorgeous, as it looks like the banner color in my app, and I think I will stick to it as a banner color in in this and the next projects.

Please make a pull request or just send me a 192x192 PNG and a 512x512 version for Google Play.

I do not like the way Google suggests doing monetization. They want it all being done thru Android Pay, and the platform only supports fiat. I am currently mad about putting my bitcoin address everywhere, so I will probably put my address in the description of every project and monetize them this way.

After you make this icon, do you want to be given credit for it? On your request I will create an "about" window in the project and put your data there, like e-mail and your address for cryptocurrency donations.

Eventually I may have people communicate thru posting messages on a blockchain, the way they do in Bitcoin Cash. Obviously some money will be needed for transactions fees then. I may even run a node and collect fees myself.

Do you know how to create an icon for an app that incorporates a noticeboard for local events? One will be able to create a community and automatically become its admin and post events. The app is going to solve the problem of following a noticeboard without creating a profile, as having one will not be necessary for reading the notice board.

The app is inspired by The Witches' Voice (Witchvox), which is a platform people use to find social and educational events in their area.

I do not know exactly what this app is going to be doing, but when it is ready in a couple of years, I may pay somebody to make an icon.

**Comment by zularizal** [comment]
Hi @syrop , I've uploaded the file to drive, you can download on this link.

https://drive.google.com/open?id=1q3YvElJ7X9ytdp2x2kWN5lEF0YrG-38K

And I have also sent a pull request for you. please check #2 

You can give credit my name and link my github profile. This icon is free for your project. I just want to help you create this icon.

icon for the app that incorporates a noticeboard for local events, I might be able to create it, do you have a project for the app?

**Comment by syrop** [comment]
Hi,
I have accepted your merge request. I see that you have also created large graphics for Play. I will upload them to Play, but I do not know whether Play still uses them. I have seen other apps on Play Store; I think Play no longer shows the large banner above application descriptions.

I have another request. Can you create an icon for notification? This will be the small icon displayed in the notification bar of Android. This will be the same icon, just without background.

The other application I am talking about is called 'Events' and is in another repository on my profile. I am not sure yet how thtis application is supposed to work. You can already create a community, but you cannot post events there. Please note that all data entered into the database at this stage may be deleted before the app goes to production.

I shall create a beta version of Navigator and post it for you to test. I encourage you to publish your bitcoin address anyway. You will not be receiving much money this way, but you will be legitimizing bitcoin and contributing to its already high value. At the same time, by exposing your bitcoin address you may be creating hype around a project you are not interested in and have no use for, so I understand that you may want to skip it.

**Comment by syrop** [comment]
I see that you are already familiar with blockchain.

It's a pity Steem is exclusive. There should be nothing wrong with receiving money from multiple sources. At the same time, it looks extremely noble when somebody makes a contribution and at the same time _does_not_ create a donation box, so that people know that you do not accept donations even if they are offered. Did you receive money for the contribution you made to my project? (You should).

I do not contribute to projects of others, so I will not be joining Utopian. I stake a large sum of money in Ark, so that newly minted coins are sent to me every day. It's passive income. I can then convert ark to bitcoin and reward creators this way.

**Comment by zularizal** [comment]
I have received some rewards for my contribution to other people's projects. After this I will make a proposal for this contribution on your project, if they accept it, they will give reward (steem) to me.

In utopian you do not have to contribute to someone else's project, you can post your own project to utopian. They have some moderators to check your project and if the project is accepted then you will receive a reward. I suggest it to you because you have skill in coding.

On the other hand I like your noble deeds on github. because you have created an open source project and shared it to github for free. I appreciate that. it was great.

You've done a good job. You save your money into ark. And you can earn passive income on it.

**Comment by syrop** [comment]
I had to further resize the product icons you sent me. When you import icons into Android Studio, there is a "resize" slider in the import dialog. Otherwise the icon will be cropped.

I have fixed it and already incorporated the product icon, as well as notification icon, into the project. It looks gorgeous.

I cannot use Utopian, as I have already published my bitcoin address in the copyright note of every file, and as you said, Utopian doesn't allow for other sources of income. If you need to rely on a central authority to grant you rewards, it's not very decentralized, is it? ;) I can use ark, bitcoin, without logging in to the 'bitcoin authority'.

I am working on the 'credits' dialog now, and I will publish the beta version on Play Store today or tomorrow.

**Comment by syrop** [comment]
The build is released to alpha channel. Thank you again! You have made my day.
Please let me know if the 'Credits' screen needs to be updated.
If you wish to become an alpha tester, please use the following address. When production version is available, you will see it in Google Play. Please note that it will not happen until I finish implementing debug functionality.

https://play.google.com/apps/testing/pl.org.seva.navigator

**Comment by zularizal** [comment]
Okay, I have installed and tried the application on my smart phone. This app is cool, you have to keep developing it.
