### ISSUE TITLE
Observables to LiveData And destroy it!

### ISSUE THREAD

**Issue by Sanchew** [syrop/Wiktor-Navigator#4]
fun <T> Observable<T>.toLiveData() : LiveData<T> =
    MutableLiveData<T>().apply {
        this@toLiveData.subscribe { value = it }
    }

you say "LiveData takes care of the lifecycle for Disposable"， but i see Disposable not dispose when LiveData destroy. 

I adopt the following solution:

fun <T> Observable<T>.toLiveData(): LiveData<T> = RxMutableLiveData<T>().apply {
    this@toLiveData.subscribe { postValue(it) }.addTo(this.disposable)
}

public class RxMutableLiveData<T> : MutableLiveData<T>() {

    public var disposable: CompositeDisposable = CompositeDisposable()

    protected fun finalize() {
        disposable.dispose()
    }

}

because i'm not kotlin developer , so what your opinion about this.

**Comment by syrop** [comment]
You're right in saying that my code above doesn't dispose the observables. Try this:

```kotlin
    fun <T> Observable<T>.toLiveData() : LiveData<T> =
    object : MutableLiveData<T>() {
        
        var disposable: Disposable? = null
        
        override fun onInactive() {
            disposable?.dispose()
        }
        
        override fun onActive() {
            disposable = subscribe { value = it }
        }
    }
```

This way you are creating a new subscription when LiveData starts being observed (the number of listeners increases from 0 to 1) and the subscription is disposed when the last listener disappears. Subscription is created again when the number of listeners again goes from 0 to 1, so use this code only if you are okay with creating more than one subscription. (Previous subscription will be disposed before a new one is created).

In your example I am not sure what ```finalize()``` is doing. Shouldn't you use ```onDestroy()``` instead? I am assuming you are using a lifecycle of an Activity or Fragment.

The solution you suggested is a standard one, and I saw it used it a professional program. Use CompositeDisposable as often as you can, unless you want to combine different kinds of data structures, such as RxJava and LiveData.

Currently I am not a huge fan of LiveData. I use StateFlow instead. StateFlow doesn't require disposing. You just set its value:

```kotlin
stateFlow.value = 0
```

You can collect StateFlow's values in a Fragment:

```kotlin
lifecycleScope.launch {
    stateFlow.collect { println("$it") }
}
```

lifecycleScope is automatically canceled when Fragment dies. (In ViewModel use viewModelScope).

You can always convert StateFlow to LiveData using the code:

```kotlin
stateFlow.toLiveData()
```
A project heavily relying on StateFlow. Requires at least Android Studio Arctic Fox:
https://github.com/syrop/Checkers

PlayStore:
https://play.google.com/store/apps/details?id=pl.org.seva.checkers

How to set up StateFlow and DataBinding:
https://syrop.github.io/jekyll/update/2021/02/21/checkers-board.html

You probably don't need RxJava at all, not even LiveData, if you use StateFlow and Data Binding. The problem is that this set requires Android Studio Arctic Fox, which is in Canary yet. If you are using an earlier version of Android Studio, you can still combine Data Binding and LiveData.

Please be advised that I haven't compiled nor run the examples I paste above. I wrote them in Android Studio, and Android Studio didn't find any errors, but you may have to correct them if they don't satisfy your needs.
